services:
  postgres:
    image: postgres:17-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: inventorydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

volumes:
  inventory_postgres_data: