"use client";
import { useCompanyText } from "@/features/companies/company-provider";
import Link from "next/link";

export function MonitoringGuide() {
  const t = useCompanyText();
  const sections = [
    ["Log", t("Ne oldu?", "What happened?"), t("API’nin tarihli olay kayıtları Loki’de tutulur (7 gün). Information normal akış, Warning beklenen ama dikkat gerektiren durum, Error başarısız işlemdir. Önce zaman aralığını ve ortamı seçin; hata kaydındaki Trace ID’yi açın. Docker/journald yerel servis kayıtları da sunucuda vardır; uygulama paneli yalnızca güvenli API kayıtlarını gösterir.", "Timestamped API events are stored in Loki (7 days). Information is normal flow, Warning needs attention, Error is a failed operation. Select time and environment, then open the Trace ID. Local Docker/journald service logs also remain on the server; this panel shows sanitized API logs.")],
    ["Trace", t("Nerede zaman harcandı?", "Where was time spent?"), t("Bir isteğin API → MediatR → veritabanı adımları aynı Trace ID altında Tempo’da tutulur (3 gün). Her adım bir span’dır. Uzun span darboğazı gösterir; ERROR span başarısız adımı gösterir. SQL ve kullanıcı verileri kaydedilmez. Kısa bir hatanın çevresindeki başarılı adımları da okuyun.", "API → MediatR → database steps share a Trace ID in Tempo (3 days). Each step is a span. Long spans reveal bottlenecks; ERROR spans reveal failures. SQL and user data are not captured. Read successful steps surrounding the failure too.")],
    ["Metric", t("Ne kadar, ne sıklıkta?", "How much, how often?"), t("CPU/RAM/disk, istek sayısı, p95 süre ve iş kuyrukları Prometheus’ta zaman serisi olarak tutulur (15 gün, en çok 3 GB). Grafana bir gösterim ve sorgu ekranıdır; bu üç veri tipinin asıl deposu değildir. Counter artan sayaçtır; rate son dönemdeki artış hızıdır. Gauge o anki değerdir. Histogram süre dağılımını ve p95’i verir.", "CPU/memory/disk, request counts, p95 and queues are Prometheus time series (15 days, at most 3 GB). Grafana is a query/display UI, not the primary store. A counter accumulates; rate is its recent growth speed. A gauge is the current value. A histogram describes duration distributions and p95.")],
    [t("Nasıl teşhis edilir?", "How to diagnose?"), "", t("1. Aktif uyarıya ve zamanı­na bakın. 2. Aynı anda CPU, RAM, p95 ve hata oranı değişmiş mi? 3. Error logundan Trace ID alın. 4. Uzun/hatalı span’ı bulun. 5. Sebebi düzelttikten sonra yeni isteklerin başarılı olduğunu ve uyarının kapandığını kontrol edin. Tek anlık CPU sıçramasına bakarak karar vermeyin; 5–10 dakikalık eğilimi izleyin.", "1. Read the alert and its time. 2. Correlate CPU, memory, p95 and errors. 3. Get the Trace ID from an error log. 4. Find the slow/failing span. 5. After fixing the cause, check fresh successful requests and resolved alerts. Use a 5–10 minute trend, not one CPU spike.")],
    [t("Bizim uygulamada önemli", "Important in this app"), "", t("Bekleyen canlı olayın yaşı artıyorsa SignalR dağıtıcısını; e-posta tekrarları artıyorsa SMTP’yi; 401/403 artıyorsa oturum ve yetkileri inceleyin. 409 genellikle aynı kaydın eşzamanlı güncellenmesidir, sunucu çökmesi değildir. Düşük stok iş uyarısıdır. Ölçüm yokluğu ile sıfırı karıştırmayın; toplayıcı kesilirse sistem sağlıklı sanılmamalı.", "Growing realtime queue age points to the dispatcher; email retries to SMTP; rising 401/403 to authentication/authorization. 409 usually means a concurrent edit, not a server crash. Low stock is a business warning. Missing metrics do not mean zero; collector outages must be visible.")],
    [t("Prova ve güvenlik", "Drill and security"), "", t("Staging’de “Hata → toparlanma” düğmesi tek istekte yapay timeout span’ı ve ERROR logu oluşturur; ardından sağlam bağlantıyla veritabanını kontrol eder. Trace’te hatalı ve başarılı adımı birlikte görün. “Gecikmeyi incele” yaklaşık 750 ms’lik span üretir. Production’da prova kapalıdır. Token, parola, e-posta, şirket adı, istek gövdesi ve SQL telemetriye eklenmez. Saklama yerel disktedir; aynı sunucu tamamen kapanırsa dış kesinti izlemesine de ihtiyaç vardır.", "On staging, Failure → recovery creates a simulated timeout span and ERROR log in one request, then checks the real database. Inspect both failed and healthy steps. Inspect latency adds a ~750 ms span. Drills are disabled in production. Tokens, passwords, email, company names, bodies and SQL are not added to telemetry. Local storage cannot monitor a full host outage; external availability monitoring is also necessary.")],
  ];
  return <div className="space-y-5"><h1 className="text-2xl font-semibold">{t("İzleme rehberi", "Monitoring guide")}</h1>
    <p className="text-sm text-muted">{t("OpenTelemetry toplar → Prometheus / Loki / Tempo saklar → Grafana ve admin paneli gösterir.", "OpenTelemetry collects → Prometheus / Loki / Tempo store → Grafana and the admin panel display.")}</p>
    {sections.map(([name, subtitle, content]) => <section key={name} className="panel p-6"><h2 className="font-semibold">{name}{subtitle && ` · ${subtitle}`}</h2><p className="mt-3 text-sm leading-7 text-muted">{content}</p></section>)}
    <Link href="/admin/monitoring" className="text-brand">← {t("Sistem izleme", "System monitoring")}</Link>
  </div>;
}
